const mentors = {
    fe: [{
            name: "Aleyna",
            surname: "Avcı",
            socialMedia: [{
                    linkedin: "https://www.linkedin.com/in/aleynaavci/",
                    displayName: "Linkedln",
                },
                {
                    github: "https://github.com/aleynaavci",
                    displayName: "GitHub",
                },
                {
                    instagram: "",
                    displayName: "Instagram",
                },
            ],
            school: "Sakarya Uygulamalı Bilimler Üniversitesi",
            exp: ["html", "css", "git", "bootstrap", "js", "react", "vscode"],
            age: 21,
            desc: "Merhaba, ben Aleyna Avcı. Sakarya Uygulamalı Bilimler Üniversitesi'nde Bilgisayar mühendisliği öğrencisiyim. Ankara'da yaşıyorum. Bir yılı aşkın süredir Front-End konusunda Javascript ve React ağırlıklı kendimi geliştirmeye çalışıyorum. Kariyerimin de bu yönde olmasını hedeflemekteyim. Mart 2023'ten bu yana Hi-Kod atölyesinde Front-End mentorluğu yapıyorum. Ayrıca kaktüsüm <a href='https://i.ibb.co/25pTVs2/IMG-20230610-WA0004.jpg' target='_blank'>Şukufe'yle</a>  birlikte Turkish psychedelic rock eşliğinde kod yazmaya bayılırım.",
            video: "https://www.youtube.com/embed/R64q1NcgH0o",
            img: "completed",
        },
        {
            name: "Ayşe Asude",
            surname: "Demirbaş",
            socialMedia: [{
                    linkedin: "https://www.linkedin.com/in/asude-demirbas-76071a223/",
                    displayName: "Linkedln",
                },
                {
                    github: "https://github.com/MorphyMitnick",
                    displayName: "GitHub",
                },
                {
                    instagram: "",
                    displayName: "Instagram",
                },
            ],
            school: "Sınav Anadolu Lisesi",
            exp: ["html", "css", "js"],
            age: 18,
            desc: "Merhabalar ben Asude. Siber güvenlik, oyun geliştirme, yapay zeka, front-end, back-end, veri bilimi, derin öğrenme ve makine öğrenmesi alanlarıyla ilgileniyorum. Kodluyoruz Jr.'de atölye gerçekleştirdim. Kodluyoruz Jr. Fellow'uyum.",
            video: "https://www.youtube.com/embed/EnJtkkiY4P0",
            img: "",
        },
        {
            name: "Ayşenur",
            surname: "Laklak",
            socialMedia: [{
                    linkedin: "https://www.linkedin.com/in/ay%C5%9Fenur-laklak-2a2915253",
                    displayName: "Linkedln",
                },
                {
                    github: "https://github.com/aysenurlaklak",
                    displayName: "GitHub",
                },
                {
                    instagram: "",
                    displayName: "Instagram",
                },
            ],
            school: "Süleyman Demirel Üniversitesi",
            exp: ["html", "css", "js"],
            age: 88,
            desc: "Ben Ayşenur Laklak. Süleyman Demirel üniversitesinde bilgisayar mühendisliği öğrencisiyim. Kitap okumayı, alışveriş yapmayı ve yeni şeyler keşfetmeyi severim.",
            video: "https://www.youtube.com/embed/rDLXNq4nVQ8",
            img: "completed",
        },
        {
            name: "Arda",
            surname: "Yüksel",
            socialMedia: [{
                    linkedin: "https://www.linkedin.com/in/arda-y%C3%BCksel-a81a02221/",
                    displayName: "Linkedln",
                },
                {
                    github: "https://github.com/yukselarda",
                    displayName: "GitHub",
                },
                {
                    instagram: "https://www.instagram.com/yukselll_arda/",
                    displayName: "Instagram",
                },
            ],
            school: " Mehmet Rıfat Evyap Mesleki ve Teknik Anadolu Lisesi",
            exp: ["html", "css", "js", "bootstrap", "csharp", "dotnet"],
            age: 16,
            desc: "Merhabalar ben Arda. Mehmet Rıfat Evyap Mesleki ve Teknik Anadolu Lisesi'nde bilişim bölümünü okuyorum. Kendimi iki yıldır Front-End alanında geliştirmeye çalışıyorum. 2023 yılının Mart ayında Kodluyoruz'da Hi-Kod Mentor görevi ile Gönüllülük sürecime başladım. Şiir yazmakla ilgileniyorum. Digimondi şirketinde eğitim görüyorum.",
            video: "https://www.youtube.com/embed/DVspdzzlObM",
            img: "completed",
        },
        {
            name: "Azat",
            surname: "Eser",
            socialMedia: [{
                    linkedin: "https://www.linkedin.com/in/azateser/",
                    displayName: "Linkedln",
                },
                {
                    github: "https://github.com/azateser",
                    displayName: "GitHub",
                },
                {
                    instagram: "",
                    displayName: "Instagram",
                },
            ],
            school: "Siirt Üniversitesi",
            exp: ["html", "css", "js", "react", "nextjs", "typescript"],
            age: 21,
            desc: "Merhabalar Ben Azat, Front-end ve UI / UX Tasarım alanına meraklı bir Web Geliştiriciyim. Ağırlıklı olarak JavaScript (ReactJS, NextJS) kullanıyorum 2020 yılından beridir Front-end alanına 2022 Yılından beridir de UI / UX Tasarım alanına ilgiliyim 2023 Yılının Mart ayında Kodluyoruza (Teknik Asistan) görevi ile Gönüllülük sürecime başladım Kodluyoruz içinde Açık Kaynak Kodluyoruz projelerinde çeşitli görevler aldım. Hİ Kod Atölyesinde yazılıma yeni başlayan insanlara Front-end alanında mentörlük yaptım ve Çeşitli projelerde UI / UX Tasarım alanında bildiklerimi Topluluk önünde anlatmaya çalıştım.",
            video: "https://www.youtube.com/embed/rm2RRSy2KLU",
            img: "completed",
        },
        {
            name: "Begüm Hilal",
            surname: "Telli",
            socialMedia: [{
                    linkedin: "https://www.linkedin.com/in/beg%C3%BCm-hilal-telli-135243264",
                    displayName: "Linkedln",
                },
                {
                    github: "https://github.com/Bhtelli",
                    displayName: "GitHub",
                },
                {
                    instagram: "https://www.instagram.com/begumh_telli/",
                    displayName: "Instagram",
                },
            ],
            school: "Süleyman Demirel Üniversitesi",
            exp: ["html", "css", "js"],
            age: 22,
            desc: "Merhaba ben Begüm, bilgisayar mühendisliği öğrencisiyim. 2 senedir bu sektörün içindeyim.  Front end web geliştirme ve backend tarafında Java ile ilgilenmekteyim. 2023 Şubat ayından beri Hi Kod Front End atölyesinde mentorlük yapıyorum. Hedefim full stack developer olmak. Amacım ise kendi versiyonumun en iyisi olup sektörde kadın gücünü göstermek! Yazılım sektöründe nice kadınları görmek ümidi ile!",
            video: "",
            img: "completed",
        },
        {
            name: "Büşra",
            surname: "Çelikçioğlu",
            socialMedia: [{
                    linkedin: "https://www.linkedin.com/in/b%C3%BC%C5%9Fra-%C3%A7elik%C3%A7io%C4%9Flu-98090619b/",
                    displayName: "Linkedln",
                },
                {
                    github: "https://github.com/busracelikcioglu",
                    displayName: "GitHub",
                },
                {
                    instagram: "",
                    displayName: "Instagram",
                },
            ],
            school: "Kocaeli Üniversitesi",
            exp: ["html", "css", "js"],
            age: 88,
            desc: "Merhaba! Ben Büşra Çelikçioğlu. 24 yaşındayım ve Kocaeli'de yaşıyorum. Kocaeli Üniversitesi'nde Bilişim Sistemleri Mühendisliği okuyorum ve aynı zamanda Bilgisayar Programcılığı mezunuyum. Yazılım geliştirme konusunda kendimi sürekli ilerletmeye çalışıyorum, özellikle Front-end web geliştirme ve Siber Güvenlik alanlarına ilgim büyük. Mezun olduğumda bu alanlarda çalışmayı hedefliyorum. Teknoloji dünyasındaki hızlı değişimleri yakından takip ederek ve kendimi geliştirmek için çaba sarf ediyorum. Ayrıca, müzik dinlemek, gezmek ve sosyal medya gibi ilgi alanlarıma da vakit ayırıyorum.",
            video: "",
            img: "completed",
        },
        {
            name: "Çağrı",
            surname: "Okan",
            socialMedia: [{
                    linkedin: " https://www.linkedin.com/in/cagriokan",
                    displayName: "Linkedln",
                },
                {
                    github: " https://github.com/ckproduces",
                    displayName: "GitHub",
                },
                {
                    instagram: "https://www.instagram.com/vckrome/",
                    displayName: "Instagram",
                },
            ],
            school: " ",
            exp: ["html", "css", "js"],
            age: 88,
            desc: "Ben Çağrı Okan. TEV İnanç Türkeş Özel Lisesi'nde eğitim görmekteyim. Tasarım, programlama ve müzik başta olmak üzere birçok alanda farklı faaliyetler göstermekteyim. Logo tasarımı, UI/UX arayüz tasarımı, müzik prodüktörlüğü ve farklı amaçlı algoritmalar üzerine çalışmalar yaptım. Son zamanlarda ise yoğunluklu olarak veri analizi ve yapay zekayı çeşitli alanlarda daha etkili şekilde kullanabilmek adına projeler geliştiriyorum. Bu alanda gelişen yenilikleri ve düşüncelerimi Senato isimli felsefe dergimde paylaşıyorum.",
            video: "",
            img: "completed",
        },
        {
            name: "Eren Efe",
            surname: "Kara",
            socialMedia: [{
                    linkedin: "https://www.linkedin.com/in/eren-efe-kara-928191261",
                    displayName: "Linkedln",
                },
                {
                    github: "https://github.com/WebDevEren",
                    displayName: "GitHub",
                },
                {
                    instagram: "",
                    displayName: "Instagram",
                },
            ],
            school: " ",
            exp: ["html", "css", "bootstrap", "js", "python"],
            age: 17,
            desc: "Ben Eren 2022'den beri yazılımla ilgileniyorum. Sürekli kendimi geliştirip yeni bilgiler öğrenmeye çalışıyorum. Hedefim Full-Stack Web Developer olup bu sektörde yer edinmek.",
            video: "https://www.youtube.com/embed/cYFAlbKJKfE",
            img: "",
        },
        {
            name: "Esmanur",
            surname: "Karataş",
            socialMedia: [{
                    linkedin: "https://www.linkedin.com/in/esmanur-karatas/",
                    displayName: "Linkedln",
                },
                {
                    github: "https://github.com/esmanur-karatas",
                    displayName: "GitHub",
                },
                {
                    instagram: "https://www.instagram.com/nur.krts_/",
                    displayName: "Instagram",
                },
            ],
            school: "",
            exp: ["html", "css", "js"],
            age: 88,
            desc: "Merhaba, ben Esmanur Karataş. 2022 yılında Fırat Üniversitesi Bilgisayar Programcılığı bölümünden mezun oldum. Şimdi de Anadolu Üniversitesi Yönetim Bilişim sistemleri okuyorum. Mezun olduktan sonra frontend alanına yönelip kendimi geliştirmeye başladım. Geliştirme sürecinde Kodluyoruz'da gönüllü teknik asistan olarak seçildim. Ayrıca frontend konusunda ilerlemem için yardımcı olabilecek insanlarla tanışmak ve bilgilerimi tazelemek amacıyla Hi-Kod 8. atölyeye başvurdum ve seçildim. Sonrasında 8. atölyede mentorluk yapmaya başladım.",
            video: "",
            img: "",
        },
        {
            name: "Furkan",
            surname: "Karagöz",
            socialMedia: [{
                    linkedin: "https://www.linkedin.com/in/furkankarag%C3%B6z/",
                    displayName: "Linkedln",
                },
                {
                    github: "https://github.com/FurkanK41",
                    displayName: "GitHub",
                },
                {
                    instagram: "https://www.instagram.com/furkan.kr41/",
                    displayName: "Instagram",
                },
            ],
            school: "Şehit Edip Zengin Anadolu Lisesi",
            exp: ["html", "css", "csharp", "dotnet"],
            age: 18,
            desc: "Merhaba ben Furkan, 18 yaşındayım, üniversite sınavına hazırlanıyorum. Bir yandan da kendimi yazılım alanında geliştiriyorum. Şuan ilgimi çeken alan Backend Web geliştirme alanı. Bugünlerde Asp.net üzerine çalışıyorum. Onun dışında Müzik dinlemek, oyun oynamak ve bisiklete binmekten hoşlanırım.",
            video: "https://www.youtube.com/embed/86NQ23OjUC0",
            img: "completed",
        },
        {
            name: "Melisa",
            surname: "Ataseven",
            socialMedia: [{
                    linkedin: "https://www.linkedin.com/in/melisa-ataseven-769473228/",
                    displayName: "Linkedln",
                },
                {
                    github: "https://github.com/MelisaAtaseven",
                    displayName: "GitHub",
                },
                {
                    instagram: "",
                    displayName: "Instagram",
                },
            ],
            school: "",
            exp: ["html", "css", "js"],
            age: 88,
            desc: "Merhaba ben Melisa. Lise dönemimde web tasarım eğitimine başlayarak temel bilgilere sahip oldum ve bu alanda deneyim kazandım. Şu an Işık Üniversitesi Bilgisayar Programcılığı son sınıf öğrencisiyim. Hedefim front-end alanında yeteneklerimi ilerletmek . Bu doğrultuda kendimi sürekli geliştirmek  için projeler üzerinde çalışarak deneyim ediniyorum.",
            video: "https://www.youtube.com/embed/F63dCwoI0cQ",
            img: "completed",
        },

        {
            name: "Nida",
            surname: "Kılıç",
            socialMedia: [{
                    linkedin: "https://www.linkedin.com/in/nida-kilic-487a35255",
                    displayName: "Linkedln",
                },
                {
                    github: "http://github.com/Nidaklc044",
                    displayName: "GitHub",
                },
                {
                    instagram: "",
                    displayName: "Instagram",
                },
            ],
            school: "Fırat Üniversitesi",
            exp: ["html", "css", "bootstrap", "react", "java", "csharp"],
            age: 21,
            desc: "Merhaba ,ismim Nida. Fırat Üniversitesi Yazılım Mühendisliği öğrencisi olarak eğitimime devam ediyorum. Kariyer hedeflerim doğrultusunda farklı alanlarda kendimi geliştiriyorum. Her fırsatta kendime yeni deneyimler katmak için itina ile çalışıyorum.",
            video: "https://youtube.com/embed/ZpM62phJPtg?feature=share",
            img: "completed",
        },
        {
            name: "Nuran",
            surname: "Bircan",
            socialMedia: [{
                    linkedin: "https://linkedin.com/in/nuranbircan",
                    displayName: "Linkedln",
                },
                {
                    github: "https://github.com/nuranbrcn",
                    displayName: "GitHub",
                },
                {
                    instagram: "https://www.instagram.com/nuranbrcn/",
                    displayName: "Instagram",
                },
            ],
            school: "Pamukkale Üniversitesi",
            exp: ["html", "css", "js"],
            age: 22,
            desc: "Merhaba ben Nuran. Pamukkale Üniversitesinde 3. Sınıf öğrencisiyim. 1 Yıldır yazılımda kendimi geliştirmeye çalışıyorum. Şu an Hi-Kod Atölyesinde Front-End Mentorluk yapıyorum.",
            video: "",
            img: "completed",
        },
        {
            name: "Seda",
            surname: "Toraman",
            socialMedia: [{
                    linkedin: "https://www.linkedin.com/in/sedanurtoraman/",
                    displayName: "Linkedln",
                },
                {
                    github: "https://github.com/SedaToraman",
                    displayName: "GitHub",
                },
                {
                    instagram: "https://www.instagram.com/trmnsedaa/",
                    displayName: "Instagram",
                },
            ],
            school: "",
            exp: ["html", "css", "js"],
            age: 88,
            desc: "Merhabalar, ben Seda Toraman. Endüstri Mühendisliği son sınıf öğrencisiyim.    Anlık hayatımın içinde dijital bir işe yer verme fikri her zaman ilgimi çekiyordu, yazılım yolculuğumda bu düşüncemle birlikte başladı. Gitar çalmayı o kadar çok seviyorum ki, hem elimde gitar hem masamda bilgisayarımla birlikte sosyal hayatımdan geri kalmadım diyebilirim. Kayak yapmayı, badminton oynamayı, gezmeyi de sevdiğim kadar Hi-Kod Atölyesiyle tanıştığımdan beri ufak da olsa projeler geliştirmek oldukça eğlenceli. ",
            video: "https://www.youtube.com/embed/gdg9oYUCgyg",
            img: "completed",
        },
        {
            name: "Selma",
            surname: "Köksal",
            socialMedia: [{
                    linkedin: "https://www.linkedin.com/in/selmakoksal/",
                    displayName: "Linkedln",
                },
                {
                    github: "https://github.com/selmakoksal",
                    displayName: "GitHub",
                },
                {
                    instagram: "https://www.instagram.com/selma.koxal/",
                    displayName: "Instagram",
                },
            ],
            school: "Gaziantep Üniversitesi",
            exp: ["html", "css", "bootstrap", "git", "vscode", "js"],
            age: 21,
            desc: "Merhabalar ben Selma. Kendimi iki yıldır Front-End alanında geliştirmeye çalışıyorum. 2023 yılının Mart ayında Kodluyoruz'da Sosyal Asistan görevi ile Gönüllülük sürecime başladım. 2022 yılı Nisan ayından beri Hi Kod Front End atölyesinde mentorlük yaparak yazılıma yeni başlayan insanlara yardımcı olmaya çalışıyorum.",
            video: "",
            img: "completed",
        },
        {
            name: "Sümeyye",
            surname: "Elgin",
            socialMedia: [{
                    linkedin: "https://www.linkedin.com/in/s%C3%BCmeyye-elgin-391060254/",
                    displayName: "Linkedln",
                },
                {
                    github: "https://github.com/s-elg",
                    displayName: "GitHub",
                },
                {
                    instagram: "https://www.instagram.com/sumeyye/",
                    displayName: "Instagram",
                },
            ],
            school: "Tekirdağ Namık Kemal Üniversitesi",
            exp: ["html", "css"],
            age: 21,
            desc: "Merhaba, ben Sümeyye! Bilgisayar mühendisliği 1. sınıf öğrencisiyim. Çanakkale'de yaşıyorum. Kendimi front-end alanında geliştirmekteyim. Hi-Kod Front-end 7. atölyesinden mezun oldum. 2023 yılının mart ayından beri gönüllü mentörlük yapmaktayım.",
            video: "https://www.youtube.com/embed/zsDaLQLA1ls",
            img: "completed",
        },
    ],
    vb: [{
            name: "Beyza",
            surname: "Önal",
            socialMedia: [{
                    linkedin: "",
                    displayName: "LinkedIn",
                },
                {
                    github: "https://github.com/stanloona64",
                    displayName: "GitHub",
                },
                {
                    instagram: "https://www.instagram.com/onlbyza/",
                    displayName: "Instagram",
                },
            ],
            school: "Karabük Üniversitesi",
            exp: ["html", "css", "js", "python", "csharp", "java", "cc", "lua"],
            age: 22,
            desc: "Merhaba, ben Beyza Önal 22 yaşındayım. Karabük Üniversitesi  Bilgisayar Mühendisliği 3. Sınıf öğrencisiyim. Veri bilimi ile 1 senedir ilgileniyorum. Hi-Kod Veri Bilimi Atölyesi'ndeki eğitimimi tamamladıktan sonra aynı atölyede mentör olarak seçildim. Şu anda yeni atölyelerde mentörlüğe devam ediyorum. Edindiğim tecrübelerle yurtdışındaki bir şirketten veri mühendisliği stajıma kabul aldım. Stajıma ve veri bilimi alanında kendimi geliştirmeye devam ediyorum. Hobilerim saz çalmak ve bilgisayar oyunları. Sizleri de Hi-Kod'a bekliyorum 🙂",
            video: "https://www.youtube.com/embed/zIwRXfjkQVE",
            img: "completed",
        },
        {
            name: "Bilge",
            surname: "Atçalı",
            socialMedia: [{
                    linkedin: "https::/www.linkedin.com/in/bilgeatcali",
                    displayName: "LinkedIn",
                },
                {
                    github: "https://github.com/atcalibilge",
                    displayName: "GitHub",
                },
                {
                    instagram: "",
                    displayName: "Instagram",
                },
            ],
            school: "",
            exp: [""],
            age: 18,
            desc: "Merhaba ben Bilge ATÇALI. Endüstri mühendisliği 3. Sınıf öğrencisiyim. Veri bilimiyle ilgileniyorum çünkü endüstri mühendisliğinin sektör, teknik, matematiksel bilgilerini veri bilimiyle harmanlayarak kariyerime devam etmek istiyorum. Bu hedef doğrultsunda Python, SQL, machine learning alanlarında çalışmalar yapıyorum.",
            video: "",
            img: "completed",
        },
        {
            name: "Emel Deniz",
            surname: "Ayvaz",
            socialMedia: [{
                    linkedin: "https://www.linkedin.com/in/emel-deniz-ayvaz-3a68b123a/",
                    displayName: "LinkedIn",
                },
                {
                    github: "https://github.com/EmelDeniz",
                    displayName: "GitHub",
                },
                {
                    instagram: "https://www.instagram.com/wheresmmind/",
                    displayName: "Instagram",
                },
            ],
            school: "Doğuş Üniversites",
            exp: [""],
            age: 20,
            desc: " Merhaba ben Emel Deniz,20 yaşındayım, Doğuş Üniversitesi Yazılım Mühendisliği 2.sınıf öğrencisiyim. Veri bilimi alanında ilerlemeyi düşünüyorum. Stajlarla birlikte kendime yeni bakış açıları katacağıma inanıyorum. Kitap okumayı, bisiklete binmeyi ve sanat alanında yeni bilgiler edinmeyi severim.",
            video: "",
            img: "",
        },
        {
            name: "Fatma Nur",
            surname: "Görmez",
            socialMedia: [{
                    linkedin: "https://www.linkedin.com/in/fatıma-nur-görmez-a57016222/",
                    displayName: "LinkedIn",
                },
                {
                    github: "https://github.com/Gormez-f",
                    displayName: "GitHub",
                },
                {
                    instagram: "https://www.instagram.com/grmezfatima/",
                    displayName: "Instagram",
                },
            ],
            school: "Dumlupınar Üniversitesi",
            exp: [""],
            age: 18,
            desc: "Merhaba, ben Fatıma Nur Görmez. Dumlupınar Üniversitesi Bilgisayar Mühendisliği 3.Sınıf öğrencisiyim.Java diliyle başladığım yolculuğumda C, C#’ la devam ettim.Basit birkaç oyun projesi yaptım.Fakat kendimi yaklaşık 7 aydır yapay zeka, veri bilimi alanında geliştiriyorum.Ve işimi de bu alanda ilerletmeyi düşünüyorum.Birkaç haftaya başlamayı düşündüğüm stajımla beraber yazılım dünyasında kendime güzel bir gelecek bekliyorum inşallah Yazılım dışında güzel yazı yazma sanatıve karakalem çizimiyle ilgileniyorum.",
            video: "",
            img: "",
        },
        {
            name: "Hilal Nur",
            surname: "Tınas",
            socialMedia: [{
                    linkedin: "https://www.linkedin.com/hilalnurtinas",
                    displayName: "Linkedin",
                },
                {
                    github: "https://github.com/hilalnurtinas",
                    displayName: "GitHub",
                },
                {
                    instagram: "",
                    displayName: "Instagram",
                },
            ],
            school: "Kocaeli Üniversitesi",
            exp: ["python", "cc", "java", "csharp", "kotlin", "html", "css", "sql"],
            age: 22,
            desc: "Merhabalar. Ben Hilal Nur Tınas. 22 yaşındayım. Kocaeli Üniversitesi Bilgisayar Mühendisliği 3. Sınıf öğrencisiyim. Veri Bilimi ile okulumda seçmeli dersim sayesinde tanıştım ve sonrasında bilgilerimi katıldığım Hi-Kod atölyesi sayesinde taçlandırdım. Atölye boyunca veri ile uğraşmaktan keyif aldım ve kendimi bu alanda geliştirme kararı aldım. Aynı zamanda şu anda atölyede mentor olarak devam etmekteyim. Kendimi bu alanda geliştirmeye ve projeler yapmaya devam ediyorum. Yaz stajımı Uyumsoft’ta software developer olarak yapmaktayım. Hobilerim müzik dinlemek, kitap okumak ve spor yapmak.",
            video: "",
            img: "completed",
        },
        {
            name: "İrem",
            surname: "Uslu",
            socialMedia: [{
                    linkedin: "https://www.linkedin.com/in/irem-u-5b05381b9/",
                    displayName: "LinkedIn",
                },
                {
                    github: "https://github.com/irem6142",
                    displayName: "GitHub",
                },
                {
                    instagram: "",
                    displayName: "Instagram",
                },
            ],
            school: "Karadeniz Teknik Üniversitesi",
            exp: [""],
            age: 21,
            desc: "Merhaba ben İrem, Karadeniz Teknik Üniversitesi yazılım mühendisliği öğrencisiyim. Daha çok veri bilimi ile ilgilensem de yapay zeka ve siber güvenlikle de ilgileniyorum. Python, sql ve java dillerinde uzmanlaşmaya çalışıyorum.Tarihi kitapları ve doğru tarihi yansıtan dizi/filmleri seviyorum. İngilizce, İtalyanca ve İspanyolca öğrenmeye çalışıyorum.Öğrendiklerimi anlatmayı sevdiğim için öğrendiğim bilgileri mediumda paylaşıyorum.Web geçmişim de vardır ama ilgimi çok çekmediği için o alana yönelmedim.",
            video: "",
            img: "",
        },
        {
            name: "Merve",
            surname: "Güzel",
            socialMedia: [{
                    linkedin: "https://www.linkedin.com/in/merve-guzel/",
                    displayName: "Linkedin",
                },
                {
                    github: "https://github.com/merv34",
                    displayName: "GitHub",
                },
                {
                    instagram: "https://www.instagram.com/merveguz3l/",
                    displayName: "Instagram",
                },
            ],
            school: "İstanbul Üniversitesi",
            exp: [""],
            age: 21,
            desc: "Merhaba ben Merve Güzel. 21 yaşındayım ve İstanbul Üniversitesi Matematik bölümünde 3.sınıf öğrencisiyim. Matematiğe ve veri bilimine tutkuyla bağlıyım. 1 seneyi aşkın bir süredir kendimi Veri Bilimi’nde geliştirmeye çalışıyorum. Hi-Kod Veri Bilimi atölyesi bu yolculukta katıldığım en verimli eğitimlerden biriydi. Burada, bu atölyede, bu insanlarla bulunmaktan çok mutluydum ve bu nedenle de bu atölyede mentor olarak devam ediyorum. Bu yolculukta öğrendiklerimi paylaşmaya, yeni şeyler öğrenmeye ve projeler geliştirmeye devam ediyorum. Aynı zamanda müzikle ilgileniyorum ve keman çalıyorum. Müzik-matematik ilişkisiyle ilgili araştırmalar yapıyorum.",
            video: "",
            img: "completed",
        },
        {
            name: "Şerife",
            surname: "Koçak",
            socialMedia: [{
                    linkedin: "https://www.linkedin.com/in/%C5%9Ferife-ko%C3%A7ak-b6966a204",
                    displayName: "Linkedin",
                },
                {
                    github: "https://github.com/serifekocak",
                    displayName: "GitHub",
                },
                {
                    instagram: "",
                    displayName: "Instagram",
                },
            ],
            school: "Konya Gıda ve Tarım Üniversitesi",
            exp: ["python", "c", "java", "csharp", "html", "css"],
            age: 22,
            desc: "Merhabalar. Ben Şerife Koçak. 22 yaşındayım. Konya Gıda ve Tarım Üniversitesi Bilgisayar Mühendisliği 3. Sınıf öğrencisiyim. Veri Bilimi ile katıldığım Hi-Kod atölyesinde tanıştım. Atölye boyunca Veri ile uğraşmaktan keyif aldım ve kendimi bu alanda geliştirme kararı aldım. Aynı zamanda şuanda atölyede mentor olarak devam etmekteyim. Şuanda da kendimi bu alanda geliştirmeye ve projeler yapmaya devam ediyorum. Yaz stajımı Aselsan'da Yazılım Tasarım biriminde yapmaktayım. Hobilerim yürüyüş yapmak ve yüzmek.",
            video: "",
            img: "completed",
        },
        {
            name: "Yusuf",
            surname: "Esat",
            socialMedia: [{
                    linkedin: "https://www.linkedin.com/in/yusufesat/",
                    displayName: "Linkedin",
                },
                {
                    github: "https://github.com/yusufesatt",
                    displayName: "GitHub",
                },
                {
                    instagram: "https://www.instagram.com/yusufeesat/",
                    displayName: "Instgaram",
                },
            ],
            school: "",
            exp: [""],
            age: 18,
            desc: " Merhaba, ben Yusuf Esat. Yazılım dünyasına Front-end olarak adım attım ve HTML, CSS, JavaScript ve Bootstrap ile farklı projeler geliştirdim. Daha sonra ise C# ile nesne yönelimli programlama konusuna odaklandım ve OOP prensiplerini kullanarak çeşitli otomasyonlar oluşturdum. Ancak ilgim daha sonra veri bilimi alanına yöneldi. Şu anda ise aktif olarak yapay zeka konusunda çalışmalar yapıyorum ve bir firma bünyesinde yapay zeka alanında staj yapıyorum. Sizlere Hi-Kod'da mentor olarak yardımcı olmaktan büyük bir mutluluk duyarım 😊 .",
            video: "https://www.youtube.com/embed/f2BE-n1LUAc",
            img: "",
        },
        {
            name: "Zeynep",
            surname: "Asarkaya",
            socialMedia: [{
                    linkedin: "https://www.linkedin.com/in/zeynep-asarkaya/",
                    displayName: "LinkedIn",
                },
                {
                    github: "https://github.com/zynpasarkaya",
                    displayName: "GitHub",
                },
                {
                    instagram: "",
                    displayName: "Instagram",
                },
            ],
            school: "",
            exp: [""],
            age: 18,
            desc: "Merhaba; Ben Zeynep; Bilgi güvenliği, kalite yönetimi ve veri analizi konularında bilgi sahibiyim. Veri analizi ve programlama becerilerimle projeler geliştirirken aynı zamanda öğrencilere eğitimler veriyorum. İyi seviyede MS Office programları, SQL, Power BI ve Python gibi araçları kullanabiliyorum. Kendini sürekli geliştirmeye odaklanan ve planlı çalışmaya önem veren biriyim. Doğayı ve çevremizi korumaya yönelik projelerde aktif olarak yer alıyorum.",
            video: "",
            img: "completed",
        },
    ],
    og: [{
            name: "Berat",
            surname: "Köksoy",
            socialMedia: [{
                    linkedin: "https://www.linkedin.com/in/beratkoksoy",
                    displayName: "LinkedIn",
                },
                {
                    github: "https://github.com/beratkoksoy",
                    displayName: "GitHub",
                },
                {
                    instagram: "https://instagram.com/beratkoksoy?igshid=MzNlNGNkZWQ4Mg==",
                    displayName: "Instagram",
                },
            ],
            school: "Tuzla Anadolu Lisesi",
            exp: ["csharp", "unity"],
            age: 18,
            desc: "Ben Berat, yaklaşık 6-7 aydır oyun geliştirme ile ilgileniyorum, çocukluğumdan beri oyunlara aşığım. Yıllardır tükettiğim bu sektöre artık birşeyler üretmenin ve hayallerimi gerçekleştirmenin farkına vardım. En büyük hayalim ise developer olmaktı. Tüm hikaye Hi-Kod'a seçilmem  ile başladı aslında. Yedeklerden girmiş olsam da o heyecanlı bekleyişlerimi unutamam. Bana bu işi öğreten saygı değer hocam Muhammet Adem Özcan ile yaptığımız dersler ile çok güzel bir temelim oldu, tabikide sadece derste bırakmayıp bende sürekli kendi başıma üzerine koydum. Şu anda hayatımda büyük yeri olan arkadaşlarım ve hocam ile tanıştım. Birlikte iş yaptığım insanları burada tanıdım. Birlikte oyunlar geliştirdik, Jam'lere katılıp güzel başarılar elde ettik. Bana gerçekten çok katkısı oldu. Daha sonra kendimi geliştirip projelere devam ettim. Şuan bir şirkette Game Developer olarak staj yapıyorum.",
            video: "https://www.youtube.com/embed/qNQmsfShrmo",
            img: "completed",
        },
        {
            name: "Berke",
            surname: "Konargöçer",
            socialMedia: [{
                    linkedin: "https://www.linkedin.com/in/berkekonargocer/",
                    displayName: "LinkedIn",
                },
                {
                    github: "https://github.com/berkekonargocer",
                    displayName: "GitHub",
                },
                {
                    instagram: "https://www.instagram.com/berkekonargocer/",
                    displayName: "Instagram",
                },
            ],
            school: "",
            age: 24,
            exp: ["csharp", "cpp", "raylib", "playfab", "unity", "unreal", "aseprite", "audacity", "github", "camtasia"],
            desc: "Çok küçük yaşlardan itibaren video oyunlarına ve arkaplanlarına duyduğu kuvvetli ilginin getirdiği tutkuyla bu sektöre yönelmiş, aktif olarak C# yazılım dili ve Unity oyun motorunu kullanarak oyunlar geliştiren Unity Oyun Geliştiricisi.",
            video: "",
            img: "completed",
        },
        {
            name: "Kaan",
            surname: "Karahancı",
            socialMedia: [{
                    linkedin: "https://www.linkedin.com/in/kaankarahanci/",
                    displayName: "LinkedIn",
                },
                {
                    "itch-io": "https://thefuturedesigner.itch.io/",
                    displayName: "Itch-io",
                },
                {
                    instagram: "https://www.instagram.com/mriyagames/",
                    displayName: "Instagram",
                },
            ],
            school: "",
            exp: ["unity", "blender", "unreal", "csharp", "adobe_premiere", "adobe_photoshop"],
            age: 20,
            desc: "Ben Kaan, 20 yaşındayım. Yaklaşık iki yıldır oyun geliştirmekle ilgileniyorum. Senarist olarak başladığım bu sürece hi-kod sayesinde programmer olarak devam ettim. Bugünlerde kendi start-up'ım içerisinde ürün yönetimi ve oyun tasarımı görevlerini üstleniyorum.",
            video: "https://www.youtube.com/embed/AtZTTBqUcPs",
            img: "",
        },
        {
            name: "Muhammed",
            surname: "Koç",
            socialMedia: [{
                    linkedin: "https://www.linkedin.com/in/muhammedkoc/",
                    displayName: "LinkedIn",
                },
                {
                    "itch-io": "https://temomein.itch.io/",
                    displayName: "Itch-io",
                },
                {
                    instagram: "https://www.instagram.com/temomein/",
                    displayName: "Instagram",
                },
            ],
            school: "Halil Rıfat Paşa MTAL",
            exp: ["unity", "csharp", "python"],
            age: 16,
            desc: "Merhaba ben Muhammed, 16 yaşındayım. 1.5 yıldır Oyun geliştirme alanında kendimi geliştiriyorum. Aynı zamanda 9 aydır pixel art tasarımlar yapıyorum. Bu yüzden şuanda pixel art oyunlar üzerinde çalışılıyorum.",
            video: "https://www.youtube.com/embed/aRW87QBpMG4",
            img: "completed",
        },
        {
            name: "Muhammet",
            surname: "Bulut",
            socialMedia: [{
                    linkedin: "https://www.linkedin.com/in/muhammetbulut/",
                    displayName: "LinkedIn",
                },
                {
                    github: "https://github.com/bunshiin",
                    displayName: "GitHub",
                },
                {
                    instagram: "",
                    displayName: "Instagram",
                },
            ],
            school: "Mehmet Rıfat Evyap MTAL",
            exp: ["html", "css", "js"],
            age: 17,
            desc: "Merhaba, ben Muhammet Bulut. 6 yaşındayken bozulan bilgisayarım sayesinde onu araştırmaya başlama merakıyla yazılım sektörüne kendimi adadım. 3.5 yıldır oyun geliştirme ve 2 yıldır da web geliştiricisi olarak projeler üretip uygulamalar geliştiriyorum.",
            video: "",
            img: "completed",
        },

    ]
}