const mentors = [{
        name: "Berat",
        surname: "Köksoy",
        socialMedia: [{
                linkedin: "https://www.linkedin.com/in/beratkoksoy",
                displayName: "LinkedIn",
            },
            {
                github: "https://github.com/beratkoksoy",
                displayName: "GitHub",
            },
            {
                instagram: "https://instagram.com/beratkoksoy?igshid=MzNlNGNkZWQ4Mg==",
                displayName: "Instagram",
            },
        ],
        school: "Tuzla Anadolu Lisesi",
        exp: ["html", "css", "git", "bootstrap", "js", "react"],
        age: 18,
        desc: "Ben Berat, yaklaşık 6-7 aydır oyun geliştirme ile ilgileniyorum, çocukluğumdan beri oyunlara aşığım. Yıllardır tükettiğim bu sektöre artık birşeyler üretmenin ve hayallerimi gerçekleştirmenin farkına vardım. En büyük hayalim ise developer olmaktı. Tüm hikaye Hi-Kod'a seçilmem  ile başladı aslında. Yedeklerden girmiş olsam da o heyecanlı bekleyişlerimi unutamam. Bana bu işi öğreten saygı değer hocam Muhammet Adem Özcan ile yaptığımız dersler ile çok güzel bir temelim oldu, tabikide sadece derste bırakmayıp bende sürekli kendi başıma üzerine koydum. Şu anda hayatımda büyük yeri olan arkadaşlarım ve hocam ile tanıştım. Birlikte iş yaptığım insanları burada tanıdım. Birlikte oyunlar geliştirdik, Jam'lere katılıp güzel başarılar elde ettik. Bana gerçekten çok katkısı oldu. Daha sonra kendimi geliştirip projelere devam ettim. Şuan bir şirkette Game Developer olarak staj yapıyorum.",
        video: "https://www.youtube.com/watch?v=qNQmsfShrmo",
        img: "conpleted",
    },
    {
        name: "",
        surname: "",
        socialMedia: [{
                linkedin: "",
                displayName: "",
            },
            {
                github: "",
                displayName: "",
            },
            {
                instagram: "",
                displayName: "",
            },
        ],
        school: "",
        exp: ["html", "css", "js"],
        age: 18,
        desc: "",
        video: "",
        img: "",
    },
    {
        name: "",
        surname: "",
        socialMedia: [{
                linkedin: "",
                displayName: "",
            },
            {
                github: "",
                displayName: "",
            },
            {
                instagram: "",
                displayName: "",
            },
        ],
        school: "",
        exp: ["html", "css", "js"],
        age: 18,
        desc: "",
        video: "",
        img: "",
    },
    {
        name: "Muhammed",
        surname: "Koç",
        socialMedia: [{
                linkedin: "https://www.linkedin.com/in/muhammedkoc/",
                displayName: "LinkedIn",
            },
            {
                github: "https://github.com/MuhammedKoc",
                displayName: "GitHub",
            },
            {
                instagram: "https://www.instagram.com/temomein/",
                displayName: "Instagram",
            },
        ],
        school: "Halil Rıfat Paşa MTAL",
        exp: ["html", "css", "js"],
        age: 16,
        desc: "Merhaba ben Muhammed, 16 yaşındayım. 1.5 yıldır Oyun geliştirme alanında kendimi geliştiriyorum. Aynı zamanda 9 aydır pixel art tasarımlar yapıyorum. Bu yüzden şuanda pixel art oyunlar üzerinde çalışılıyorum.",
        video: "Projemin video linki: https://youtu.be/aRW87QBpMG4",
        img: "comleted",
    },
    {
        name: "",
        surname: "",
        socialMedia: [{
                linkedin: "",
                displayName: "",
            },
            {
                github: "",
                displayName: "",
            },
            {
                instagram: "",
                displayName: "",
            },
        ],
        school: "",
        exp: ["html", "css", "js"],
        age: 18,
        desc: "",
        video: "",
        img: "",
    },
]