const mentors = [{
        name: "",
        surname: "",
        socialMedia: [{
                linkedin: "",
                displayName: "",
            },
            {
                github: "",
                displayName: "",
            },
            {
                instagram: "",
                displayName: "",
            },
        ],
        school: "",
        exp: ["html", "css", "git", "bootstrap", "js", "react"],
        age: 21,
        desc: "",
        video: "",
        img: "",
    },
    {
        name: "",
        surname: "",
        socialMedia: [{
                linkedin: "",
                displayName: "",
            },
            {
                github: "",
                displayName: "",
            },
            {
                instagram: "",
                displayName: "",
            },
        ],
        school: "",
        exp: ["html", "css", "js"],
        age: 18,
        desc: "",
        video: "",
        img: "",
    },
    {
        name: "",
        surname: "",
        socialMedia: [{
                linkedin: "",
                displayName: "",
            },
            {
                github: "",
                displayName: "",
            },
            {
                instagram: "",
                displayName: "",
            },
        ],
        school: "",
        exp: ["html", "css", "js"],
        age: 18,
        desc: "",
        video: "",
        img: "",
    },
    {
        name: "",
        surname: "",
        socialMedia: [{
                linkedin: "",
                displayName: "",
            },
            {
                github: "",
                displayName: "",
            },
            {
                instagram: "",
                displayName: "",
            },
        ],
        school: "",
        exp: ["html", "css", "js"],
        age: 18,
        desc: "",
        video: "",
        img: "",
    },
    {
        name: "",
        surname: "",
        socialMedia: [{
                linkedin: "",
                displayName: "",
            },
            {
                github: "",
                displayName: "",
            },
            {
                instagram: "",
                displayName: "",
            },
        ],
        school: "",
        exp: ["html", "css", "js"],
        age: 18,
        desc: "",
        video: "",
        img: "",
    },
]